# Generated by Django 5.1 on 2024-08-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(default='default@example.com', max_length=254)),
                ('sedula', models.CharField(default='00000000', max_length=200)),
                ('description', models.TextField(default='Sin descripción')),
                ('plan', models.CharField(choices=[('I', 'Individual'), ('A', 'Amigos')], default='I', max_length=1)),
            ],
        ),
    ]
